database:
  type: "sqlite" # "mysql" or "sqlite"
  host: "localhost"
  port: 3306
  database: "statusup"
  username: "root"
  password: "password"

sounds:
  enabled: true
  upgrade-success-sound:
    name: "ENTITY_PLAYER_LEVELUP"
    volume: 1.0
    pitch: 1.0
  upgrade-fail-sound:
    name: "ENTITY_VILLAGER_NO"
    volume: 1.0
    pitch: 1.0

broadcast:
  rankup: true
  starup: true

discord-webhook:
  enabled: false
  webhook-url: "YOUR_WEBHOOK_URL_HERE"
  embed:
    color: 3447003 # Decimal color code
    author-name: "StatusUp Notifications"
    author-icon-url: ""

main-gui:
  title: "&1&lStatusUP"
  size: 27
  fill-glass:
    enabled: true
    material: "BLACK_STAINED_GLASS_PANE"
    name: " "
  rankup-item:
    material: "NETHER_STAR"
    name: "&a&lRankUP"
    lore:
      - "&7Click to view ranks!"
      - ""
      - "&eYour Rank: &f%statusup_rank_name%"
    slot: 12
  starup-item:
    material: "BEACON"
    name: "&b&lStarUP"
    lore:
      - "&7Click to view stars!"
      - ""
      - "&eYour Stars: &f%statusup_star_name%"
    slot: 14